name: Compile and Release

on:
  release:
    types: [released]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run compile
      - name: Add Artifact to Workflow
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            release/*.AppImage

  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run compile
      - name: Add Artifact to Workflow
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            release/*.exe
